%{
#pragma GCC diagnostic ignored "-Wunused-function"
#include <iostream>
#include "term.hpp"
#include "parser.tab.hpp"
%}

%option noyywrap

%%

[A-Z][a-zA-Z0-9_]* { yylval.str = strdup(yytext); return VAR; }

[a-z][a-zA-Z0-9_]* { yylval.str = strdup(yytext); return SYMBOL; }

~ { return NOT; }

& { return AND; }

\| { return OR; }

=> { return IMPLIES; }

\<=\> { return IFF; }

! { return FORALL; }

\? { return EXISTS; }

[ \t\n]+ { }

. { return *yytext; }

%%

